### ISSUE TITLE
Add HTTP and REST gw addresses

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/status-fs-neo-org#95]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when people can't find GW addresses.

## Describe the solution you'd like
Put them onto the page. Add a disclaimer that these are public gateways that MUST NOT be used for production applications, they're a centralization point and they're not guaranteed to always be available. But they can be used for test purposes. Name them "Test gateways".

**Comment by mike-petrov** [comment]
Do you mean `https://rest.t5.fs.neo.org/v1` and `https://http.t5.fs.neo.org`?
We should add it for both pages: testnet and mainnet?

**Comment by roman-khimov** [comment]
Yeah, we have them both for T5 and mainnet.
